version: '3'
services:
  workspace:
    build: ./workspace
    working_dir: /var/www/SPA
    env_file: 
      - .env
    volumes:
      - ./src/api:/var/www/SPA
      - ./log/nginx:/var/log/nginx
      - ./log/php-fpm:/var/log/php-fpm
    tty: true

  nginx:
    image: nginx:1.19-alpine
    ports: 
      - "8080:80"
      # - "1443:443" SSL
    working_dir: /var/www/SPA
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/api:/var/www/SPA
      - ./log/nginx:/var/log/nginx
      - ./php-fpm/sock:/var/run/php-fpm

  php-fpm:
    build: ./php-fpm
    # ports:
    #   - "9000:9000" xdebug
    working_dir: /var/www/SPA
    env_file: 
      - .env
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./src/api:/var/www/SPA
      - ./log/php-fpm:/var/log
      - ./php-fpm/sock/:/var/run/php-fpm/

  pgsql:
    image: postgres:12.3-alpine
    env_file: 
      - .env
    volumes:
      - ./pgsql/data/:/var/lib/postgresql/data/




